In [1]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)

m = 100
x1 = 50 + 30 * np.random.rand(m,1)
y = 135 + 0.5 * x1 + 3 * np.random.randn(m,1)

In [3]:
#資料前處理(preprocessing)
#Feature標準化

from sklearn.preprocessing import StandardScaler

scal = StandardScaler()
x1Scal = scal.fit_transform(x1)   #將x1的數據標準化

x1Scal[:5]

array([[-0.23388437],
       [ 0.79634961],
       [-1.65000333],
       [-0.62345239],
       [-1.15190299]])

In [4]:
scal.mean_, scal.scale_    #顯示出x1的平均數與標準差

(array([64.57633783]), array([8.83204675]))

In [7]:
from sklearn.linear_model import SGDRegressor

sgdReg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=.1)       #對函數內參數進行調整：執行1000步，容許誤差值為十的負三次方，學習數率初始值為0.1
sgdReg.fit(x1Scal,y.ravel())        #用標準化後的x1與y製作模型，ravel將y從1*100轉化成100*1

sgdReg.intercept_, sgdReg.coef_      #顯示出模型內的b與w

(array([167.51475813]), array([4.15206458]))

In [8]:
#加入新的x1進行預測

x1New = [[50],[80]]
x1NewScal = scal.transform(x1New) #將新的x1使用之前已計算出的平均數與標準差進行標準化

In [9]:
sgdReg.predict(x1NewScal)    #使用已經計算出的模型預測y

array([160.66222465, 174.76563024])