In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets
iris = datasets.load_iris()

x = iris['data']
y = iris['target']

In [5]:
#一對多 OVR
#使用 OneVsRestClassifier()

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression(random_state=1)
ovrClf = OneVsRestClassifier(logReg)

ovrClf.fit(x, y)

OneVsRestClassifier(estimator=LogisticRegression(random_state=1))

In [6]:
ovrClf.score(x, y)

0.9533333333333334

In [7]:
yPred = ovrClf.predict(x)
yPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, yPred)

array([[50,  0,  0],
       [ 0, 45,  5],
       [ 0,  2, 48]], dtype=int64)

In [9]:
#使用LogisticRegression()

ovrLog = LogisticRegression(multi_class='ovr', random_state=1)
ovrLog.fit(x, y)

LogisticRegression(multi_class='ovr', random_state=1)

In [10]:
ovrLog.score(x, y)

0.9533333333333334

In [11]:
yPred = ovrLog.predict(x)
yPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
confusion_matrix(y, yPred)

array([[50,  0,  0],
       [ 0, 45,  5],
       [ 0,  2, 48]], dtype=int64)

In [15]:
#一對一 OVO
#使用 OneVsOneClassifier()

from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import SVC

svcClf = SVC(random_state=1)
ovoClf = OneVsOneClassifier(svcClf)
ovoClf.fit(x, y)

OneVsOneClassifier(estimator=SVC(random_state=1))

In [16]:
ovoClf.score(x, y)

0.9733333333333334

In [17]:
yPred = ovoClf.predict(x)
yPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
confusion_matrix(y, yPred)

array([[50,  0,  0],
       [ 0, 48,  2],
       [ 0,  2, 48]], dtype=int64)

In [19]:
#使用SVC()

ovoSvc = SVC(decision_function_shape='ovo', random_state=1)
ovoSvc.fit(x, y)

SVC(decision_function_shape='ovo', random_state=1)

In [20]:
ovoSvc.score(x, y)

0.9733333333333334

In [21]:
yPred = ovoSvc.predict(x)
yPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
confusion_matrix(y, yPred)

array([[50,  0,  0],
       [ 0, 48,  2],
       [ 0,  2, 48]], dtype=int64)